version: "3.9"
services:
  webapi:
    build:
      context: ./SudoquApi
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  reactapp:
    build:
      context: ./sudoqureact
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge