version: "3.9"
services:
  webapi:
    build:
      context: ./SudoquApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000

  reactapp:
    build:
      context: ./sudoqureact
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge